Show chain of causes of RepoException if they reach main()
This is needed to see the NotRoundtrippableException cause if it is
thrown by the Replace transform. This also removes the transform
toString() from the cause. The output upon transform failure now looks
like:

ERROR: Error applying transformation: Replace{before=[{@, LITERAL}, {libname, INTERPOLATION}, {//jar, LITERAL}], after=[{//third_party/java/, LITERAL}, {libname, INTERPOLATION}], regexGroup={libname=[^/@]+}, fileMatcher=sun.nio.fs.UnixFileSystem$3@1c3a4799}
  CAUSED BY: Text '        "@autocommon//jar",' reverse-transforms to different string: '        "@autocommon",//jar'

Change-Id: I20979e86410d809b33a92dde0384cd93649c2fb5
GitOrigin-RevId: ba1220203a9efa3343ea8dd34986927fdd88ec9a